export const DEFAULT_EQUIPMENT = [
  "PRECONDITIONING",
  "CHAMBER #1",
  "CHAMBER #2",
  "CHAMBER #4",
  "CHAMBER #5",
  "DEGASSING #1",
  "DEGASSING #2",
  "DEGASSING #3",
  "DEGASSING #4",
  "EO ROOM",
  "CHILLER UNITS",
  "BOILER UNITS",
  "CRO SYSTEM",
  "OXIDIZER SYSTEM",
  "NITROGEN SYSTEM",
  "GENERAL FACILITIES",
];

export const DEFAULT_CATEGORIES = [
  "Couplings",
  "Fuses",
  "Bearings",
  "Belts",
  "Hardware",
  "Seals",
  "Filters",
  "Electrical",
  "Valves",
  "Sensors",
  "Other",
];

export const SAMPLE_PARTS = [
  {
    partNumber: "32ZP74",
    description: "TB WOOD'S Sleeve Coupling Insert 8 Coupling Size 4500 RPM",
    manufacturer: "TB WOODS",
    modelSerial: "8E",
    qty: 3,
    reorderQty: 0,
    leadTimeDays: 0,
    usedIn: ["CHAMBER #4"],
    equivalentPN: "",
    storageLocationId: "",
    category: "Couplings",
    notes: "",
  },
  {
    partNumber: "32ZP75",
    description: "TB WOOD'S Sleeve Coupling Insert 9 Coupling Size 3750 RPM 2340 in-lb",
    manufacturer: "TB WOODS",
    modelSerial: "9E",
    qty: 2,
    reorderQty: 1,
    leadTimeDays: 0,
    usedIn: ["CHAMBER #1", "CHAMBER #2"],
    equivalentPN: "",
    storageLocationId: "",
    category: "Couplings",
    notes: "",
  },
  {
    partNumber: "4YZD8",
    description: "MERSEN Fuse Class RK5 Time-Delay 20A 250V AC",
    manufacturer: "MERSEN",
    modelSerial: "TR20R",
    qty: 6,
    reorderQty: 0,
    leadTimeDays: 0,
    usedIn: [],
    equivalentPN: "",
    storageLocationId: "",
    category: "Fuses",
    notes: "",
  },
  {
    partNumber: "4YZN3",
    description: "MERSEN Fuse Class RK5 TRS-R Time-Delay 60A 600V AC",
    manufacturer: "MERSEN",
    modelSerial: "TRS60R",
    qty: 11,
    reorderQty: 0,
    leadTimeDays: 0,
    usedIn: [],
    equivalentPN: "",
    storageLocationId: "",
    category: "Fuses",
    notes: "",
  },
  {
    partNumber: "2PA66",
    description: "Worm Gear Hose Clamp Interlocked 3/4 in Band Width 10 PK",
    manufacturer: "MISC",
    modelSerial: "5764",
    qty: 0,
    reorderQty: 0,
    leadTimeDays: 0,
    usedIn: ["CHAMBER #1", "CHAMBER #2", "CHAMBER #4", "CHAMBER #5"],
    equivalentPN: "",
    storageLocationId: "",
    category: "Hardware",
    notes: "",
  },
];
